version: "3.8"

services:
  app:
    build:
      context: .
      target: dev # Use 'production' for production
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app # For development: mount the code for live reload
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: starter
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
